"""обнова таблицы с продуктами с is_crotical

Revision ID: b2b452c9d3d6
Revises: 2e5bd1f32162
Create Date: 2026-05-05 23:40:53.414113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b452c9d3d6'
down_revision: Union[str, Sequence[str], None] = '2e5bd1f32162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
